# @genqlient(for: "Template.name")
# @genqlient(for: "Template.type")
# @genqlient(for: "Template.templateData")
fragment Template on Template {
  id
  team {
    id
  }
  name
  description
  type
  templateData
}
  
query getTemplate($id: String!) {
  template(id: $id) {
    ...Template
  }
}

# @genqlient(for: "TemplateCreateInput.id", pointer: true)
# @genqlient(for: "TemplateCreateInput.teamId", pointer: true)
# @genqlient(for: "TemplateCreateInput.name", pointer: true)
# @genqlient(for: "TemplateCreateInput.description", pointer: true)
# @genqlient(for: "TemplateCreateInput.type", pointer: true)
# @genqlient(for: "TemplateCreateInput.data", pointer: true)
mutation templateCreate(
  $input: TemplateCreateInput!
) {
  templateCreate(input: $input) {
    template {
      ...Template
    }
  }
}

mutation templateUpdate(
  $input: TemplateUpdateInput!,
  $id: String!
) {
  templateUpdate(input: $input, id: $id) {
    template {
      ...Template
    }
  }
}

mutation templateDelete($id: String!) {
  templateDelete(id: $id) {
    success
  }
}
